### ISSUE TITLE
[2pt] Create a Crowdin-project for try-tarantool

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/try#32]
- [x] Завести проект https://crowdin.com/project/try-tarantool
- [x] Добавить конфиги в репозиторий
- [x] Запушить в первый раз строки и переводы

Сначала нужно, чтобы в репозитории разделили файлы на ./en/ и ./ru/. Подробности тут https://www.notion.so/tarantool/e70da95c62484eb8a82f48aa7518c227

Конфиг будет выглядеть как-то так:

```yaml
files:
  - source: /foo/en/*.md
    translation: /foo/ru/%file_name%.md
```
